In [1]:
import tensorflow as tf
import gym
import numpy as np
from collections import deque

offene Probleme / mögliche Verbesserungen:
    - in einem Endzustand nicht mehr q(a',s') berechnen
    - Minibatch mit TF erzeugen
    - store old network weights and use them in loss function

In [2]:
# build graph
obs_dim = 4
n_acts = 2
gamma = 0.9

obs_ph = tf.placeholder(shape=(None, obs_dim), dtype=tf.float32)
act_ph = tf.placeholder(shape=(None, 1), dtype=tf.int32)
rew_ph = tf.placeholder(shape=(None, 1), dtype=tf.float32)
new_obs_ph = tf.placeholder(shape=(None, obs_dim), dtype=tf.float32)

# make core of state-action-value function network
mlp_action_val = tf.keras.models.Sequential()
mlp_action_val.add(tf.keras.layers.Dense(10, activation='tanh'))
mlp_action_val.add(tf.keras.layers.Dense(10, activation='tanh'))
mlp_action_val.add(tf.keras.layers.Dense(n_acts))

# define state action values
old_state_action_values = mlp_action_val(obs_ph)
new_state_action_values = mlp_action_val(new_obs_ph)

# select action
greedy_action = tf.math.argmax(old_state_action_values)

# define loss function
y = rew_ph + gamma * np.max(new_state_action_values)
y_tensor = tf.identity(y)
action_masks = tf.one_hot(act_ph, n_acts)
old_selected_action_values = tf.reduce_sum(action_masks * old_state_action_values, axis=1)
action_value_loss = tf.reduce_mean((y_tensor - old_selected_action_values)**2)

# define optimizer
optimizer_action_value = tf.train.AdamOptimizer(0.0001)
train_action_value = optimizer_action_value.minimize(action_value_loss)


In [3]:
def dqn(sess, env, experience_replay_buffer, n_episodes):
    for i in range(n_episodes):
        done = False
        state = env.reset()
        cnt = 0
        while not done:
            action = select_action(sess, state)
            new_state, reward, done, _ = env.step(action)
            experience_replay_buffer.append((state, action, reward, new_state))
            state = new_state
            update_q_function(experience_replay_buffer)
            cnt += 1
        print(i, cnt)
        
        
def update_q_function(experience_replay_buffer):
    experience_batch = sample_experience_batch(experience_replay_buffer)
    states, actions, rewards, new_states = extract_data(experience_batch)
    loss = gradient_step(states, actions, rewards, new_states)

def gradient_step(states, actions, rewards, new_states):
    _, loss = sess.run([train_action_value, action_value_loss], feed_dict={
                                obs_ph: np.array(states).reshape(-1, obs_dim),
                                act_ph: np.array(actions).reshape(-1,1),
                                rew_ph: np.array(rewards).reshape(-1,1),
                                new_obs_ph: np.array(new_states).reshape(-1,obs_dim)
                             })
    return loss
    
def extract_data(experience_batch):
    states = [x[0] for x in experience_batch]
    actions = [x[1] for x in experience_batch]
    rewards = [x[2] for x in experience_batch]
    new_states = [x[3] for x in experience_batch]
    return states, actions, rewards, new_states
    
def sample_experience_batch(experience_replay_buffer, batch_size=100):
    indices = np.random.choice(np.arange(len(experience_replay_buffer)), batch_size)
    tmp = np.array(experience_replay_buffer)
    sample_batch = tmp[indices, :]
#     sample_batch = np.random.choice(experience_replay_buffer,batch_size, replace = False)
    return sample_batch

def select_action(sess, state):
    print(sess.run(old_state_action_values, {obs_ph: state.reshape(1,-1)}))
    action = 0
    if np.random.rand() < 0.1:
        action = np.random.randint(2)
    else:
        action = sess.run(greedy_action, {obs_ph: state.reshape(1,-1)})[0]
    return action

In [4]:
# main
exp_replay_size = 5000
experience_replay_buffer = deque([], exp_replay_size)
env = gym.make('CartPole-v0')

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

dqn(sess, env, experience_replay_buffer, 1000)

[[ 0.00245213 -0.00102579]]
[[-0.6048982  -0.03489596]]
[[-0.00898822 -0.00102801]]
[[0.5879381  0.03219982]]
[[1.0671582  0.08317722]]
[[1.3985177  0.14693616]]
[[1.6118941  0.21083874]]
[[1.7460377  0.26798567]]
[[1.8305894  0.31653166]]
[[1.8854171  0.35678697]]
[[1.9232144  0.38983795]]
[[1.9518894  0.41695186]]
0 12
[[-0.0329962  -0.00663375]]
[[0.55599916 0.02455158]]
[[1.0318407 0.0732414]]
[[1.3631343  0.13579528]]
[[1.5776209  0.19965942]]
[[1.7129523 0.2573998]]
[[1.7984223  0.30671537]]
[[1.8538605  0.34769523]]
[[1.8272506 0.324812 ]]
[[1.878658   0.36381692]]
1 10
[[-0.087456   -0.00147528]]
[[0.52595717 0.0293291 ]]
[[1.0263165  0.08084802]]
[[1.3691695  0.14646696]]
[[1.584478   0.21135508]]
[[1.7157393 0.268372 ]]
[[1.7963088  0.31612447]]
[[1.8477757  0.35535198]]
2 8
[[ 0.01515056 -0.00093024]]
[[0.60593337 0.03080727]]
[[1.0702083  0.08360822]]
[[1.3831737  0.14878464]]
[[1.579478   0.21259281]]
[[1.6999483  0.26860937]]
[[1.7746314  0.31552592]]
[[1.8229766 0.354001

[[0.75860935 0.08930148]]
[[0.8302689 0.1299235]]
[[0.88242364 0.16682625]]
[[0.9228618  0.19893977]]
[[0.9566144  0.22619715]]
34 12
[[-0.2811248  -0.02234822]]
[[ 0.02648361 -0.02431321]]
[[-0.30207714 -0.02061334]]
[[ 0.00609336 -0.0229489 ]]
[[ 0.2793358  -0.01607199]]
[[0.4880658  0.00776046]]
[[0.6350437  0.04391325]]
[[0.73615927 0.0847568 ]]
[[0.8069375 0.1248087]]
[[0.8588398  0.16124572]]
[[0.89945674 0.19297393]]
[[0.9336559 0.219957 ]]
35 12
[[-0.25385895 -0.02579131]]
[[ 0.05820408 -0.02846308]]
[[ 0.32611898 -0.01689102]]
[[0.5247822  0.01285782]]
[[0.6619246  0.05324514]]
[[0.7554577  0.09607606]]
[[0.8211694  0.13642667]]
[[0.8700689  0.17211702]]
[[0.90921503 0.2026245 ]]
36 9
[[-0.26505476 -0.02777559]]
[[ 0.03779931 -0.03110453]]
[[ 0.29935068 -0.02163012]]
[[0.4951384  0.00566403]]
[[0.63168675 0.04424028]]
[[0.725734   0.08613062]]
[[0.7923037 0.1262012]]
[[0.8420322  0.16200817]]
[[0.88175875 0.19279845]]
[[0.91587836 0.2187659 ]]
37 10
[[-0.2568031  -0.03098299]]

[[ 0.26318687 -0.00162203]]
[[0.33951518 0.03487225]]
[[0.3999224  0.07044154]]
[[0.45045865 0.10257274]]
69 10
[[-0.3911871 -0.0327932]]
[[-0.2049654  -0.04521145]]
[[-0.03421709 -0.05023104]]
[[ 0.10094456 -0.03947797]]
[[ 0.20171535 -0.01526536]]
[[0.277787   0.01605586]]
[[0.3382417  0.04916882]]
[[0.38912985 0.08084057]]
[[0.43389314 0.10945958]]
[[0.47465244 0.13449486]]
70 10
[[-0.38336787 -0.03286212]]
[[-0.1919653  -0.04642267]]
[[-0.01691885 -0.049592  ]]
[[ 0.12030894 -0.03525278]]
[[ 0.22179432 -0.00765099]]
[[0.2981517  0.02595714]]
[[0.3587776  0.06016196]]
[[0.40971902 0.09198707]]
[[0.45448375 0.12015058]]
71 9
[[-0.4186898  -0.03906746]]
[[-0.23554695 -0.05098052]]
[[-0.4253392  -0.03754971]]
[[-0.24256298 -0.0495597 ]]
[[-0.06919362 -0.05586331]]
[[ 0.07108364 -0.04650043]]
[[ 0.17655244 -0.02274515]]
[[0.25616583 0.00899522]]
[[0.3191175 0.0429508]]
[[0.3717535  0.07555804]]
[[0.41783178 0.10504454]]
[[0.40631196 0.08951818]]
72 12
[[-0.4175379 -0.0385832]]
[[-0.2362

[[ 0.14196336 -0.00266324]]
[[0.21307607 0.03396069]]
[[0.17248508 0.00782873]]
[[0.24436763 0.04600804]]
105 10
[[-0.43101612 -0.03901932]]
[[-0.5658089  -0.03472101]]
[[-0.6550431 -0.0463405]]
[[-0.57479733 -0.03450311]]
[[-0.45244196 -0.03492838]]
[[-0.30581522 -0.04458464]]
[[-0.16390023 -0.05149001]]
[[-0.0460922  -0.04563437]]
[[ 0.0454301  -0.02634166]]
[[-0.0427295  -0.04300939]]
[[ 0.05353343 -0.02293466]]
[[-0.03313062 -0.0405639 ]]
[[ 0.06662285 -0.01875798]]
[[0.14403383 0.01159265]]
[[0.2071319 0.0445858]]
[[0.26141888 0.07652736]]
[[0.30999708 0.10554998]]
106 17
[[-0.3920163  -0.03636421]]
[[-0.23250403 -0.0480755 ]]
[[-0.08640239 -0.04819702]]
[[ 0.02960001 -0.03151102]]
[[ 0.11826718 -0.00286474]]
[[0.18839616 0.03080272]]
[[0.24704671 0.06452613]]
[[0.29843912 0.09563681]]
107 8
[[-0.4395768  -0.03563023]]
[[-0.29110438 -0.04561709]]
[[-0.14936106 -0.05130895]]
[[-0.03289153 -0.04343119]]
[[ 0.0572649  -0.02231401]]
[[0.12828627 0.00677165]]
[[0.1873026  0.03865724]]


[[-0.3097612  -0.04954781]]
[[-0.16925934 -0.05508791]]
[[-0.05234063 -0.04744839]]
[[ 0.03878919 -0.02629047]]
[[0.11073021 0.00318953]]
[[ 0.0518722  -0.02142257]]
[[0.1276331  0.00962688]]
[[0.18996389 0.04324844]]
[[0.24397635 0.07571851]]
[[0.29246095 0.10514393]]
[[0.33698153 0.13087353]]
138 12
[[-0.4183032  -0.03186757]]
[[-0.26996994 -0.04239717]]
[[-0.1304349  -0.04622226]]
[[-0.01760199 -0.03532946]]
[[ 0.06924304 -0.01160974]]
[[0.13807508 0.01902591]]
[[0.19593592 0.05146121]]
[[0.24707112 0.08251829]]
[[0.29373357 0.11063915]]
[[0.33700556 0.13523233]]
139 10
[[-0.41360334 -0.03885005]]
[[-0.2575268  -0.05038502]]
[[-0.11064704 -0.05114351]]
[[ 0.00777866 -0.03485687]]
[[-0.09236935 -0.05075178]]
[[-0.21950008 -0.05559293]]
[[-0.0708087  -0.05065075]]
[[ 0.04700098 -0.02774818]]
[[0.13719557 0.00580707]]
[[0.20859332 0.04242083]]
[[0.26814356 0.07739842]]
140 11
[[-0.41857445 -0.04775465]]
[[-0.2666678  -0.05763966]]
[[-0.125073   -0.05857503]]
[[-0.01036446 -0.04373001]]

169 10
[[-0.41068432 -0.04520615]]
[[-0.2565156  -0.05596576]]
[[-0.11273652 -0.05604588]]
[[ 0.0030917  -0.03937939]]
[[ 0.09247547 -0.01024674]]
[[0.1635328  0.02429935]]
[[0.22304757 0.05902195]]
[[0.27515638 0.09105942]]
[[0.3221798  0.11925552]]
170 9
[[-0.39034227 -0.04315007]]
[[-0.2353463  -0.05370895]]
[[-0.09401772 -0.05197867]]
[[ 0.01849577 -0.03347912]]
[[ 0.10517894 -0.00342793]]
[[0.17446959 0.03120837]]
[[0.2328678  0.06550491]]
[[0.20717984 0.0435243 ]]
[[0.26680362 0.07836528]]
171 9
[[-0.41035098 -0.0354978 ]]
[[-0.26213795 -0.04631006]]
[[-0.12508883 -0.04886865]]
[[-0.0146602 -0.036297 ]]
[[ 0.07082583 -0.01136483]]
[[0.13908896 0.01986126]]
[[0.19670524 0.05243312]]
[[0.24765928 0.08334565]]
[[0.294075   0.11114985]]
[[0.33714363 0.1354079 ]]
172 10
[[-0.395388   -0.03680213]]
[[-0.24168746 -0.04798637]]
[[-0.09986367 -0.04827859]]
[[ 0.01310055 -0.03199791]]
[[ 0.09968609 -0.00358729]]
[[0.16858391 0.03007251]]
[[0.22669217 0.06392541]]
[[0.27798697 0.09522065]]


[[0.11208566 0.0073938 ]]
[[0.16898762 0.03908348]]
[[0.21956949 0.07007564]]
[[0.26590693 0.09854645]]
[[0.30909193 0.12374566]]
202 10
[[-0.40020245 -0.03621009]]
[[-0.2549916  -0.04671789]]
[[-0.12188835 -0.04942571]]
[[-0.01531355 -0.03746592]]
[[ 0.0670104  -0.01326778]]
[[0.13287805 0.01731762]]
[[0.18896392 0.04949199]]
[[0.23896092 0.08020858]]
[[0.28487244 0.10801394]]
[[0.3276034  0.13233575]]
203 10
[[-0.42126322 -0.0315757 ]]
[[-0.27409303 -0.04330562]]
[[-0.1351292  -0.04773342]]
[[-0.02239339 -0.03688403]]
[[ 0.06472689 -0.01297593]]
[[0.13391346 0.01782489]]
[[0.19209103 0.05033243]]
[[0.24347746 0.08136725]]
[[0.2256095  0.06308575]]
[[0.27856386 0.09433603]]
204 10
[[-0.40681666 -0.04288112]]
[[-0.25602853 -0.05357163]]
[[-0.11588464 -0.05468598]]
[[-0.00320202 -0.03964528]]
[[ 0.08372171 -0.01202247]]
[[0.15288156 0.02142312]]
[[0.21108678 0.05552102]]
[[0.26232025 0.08727611]]
[[0.30883548 0.11543921]]
205 9
[[-0.4018966  -0.04450204]]
[[-0.2474433 -0.0556547]]
[[-0.

[[ 0.07185937 -0.01454419]]
[[0.14363253 0.0181502 ]]
[[0.20333588 0.05210908]]
[[0.2554827  0.08411852]]
[[0.30257472 0.11270095]]
232 9
[[-0.39429808 -0.03798648]]
[[-0.2478357 -0.0479102]]
[[-0.11447498 -0.0493967 ]]
[[-0.00811106 -0.03606299]]
[[ 0.0739876  -0.01072543]]
[[0.13976012 0.02066636]]
[[0.19558056 0.05324843]]
[[0.24528196 0.08408471]]
[[0.29081833 0.11179163]]
[[0.33322513 0.13593495]]
233 10
[[-0.41623232 -0.03797952]]
[[-0.2653203  -0.04923676]]
[[-0.12265724 -0.05170048]]
[[-0.00732593 -0.03793227]]
[[ 0.08132485 -0.01112013]]
[[0.1514831  0.02195159]]
[[0.21015789 0.05588864]]
[[0.2617458  0.08764487]]
[[0.30842906 0.11582111]]
234 9
[[-0.44004923 -0.03769074]]
[[-0.2923166  -0.04880101]]
[[-0.14937237 -0.05355417]]
[[-0.03165247 -0.04293829]]
[[ 0.05945859 -0.01861885]]
[[0.13129678 0.0130663 ]]
[[0.19109361 0.04659397]]
[[0.24339007 0.07856733]]
[[0.29065984 0.10735524]]
[[0.33417973 0.13238257]]
235 10
[[-0.43556982 -0.03556447]]
[[-0.2874527  -0.04701144]]
[[-0

[[-0.15246761 -0.05103762]]
[[-0.03846826 -0.04213516]]
[[ 0.04986864 -0.0196521 ]]
[[0.11969047 0.01045443]]
[[ 0.06758682 -0.01370281]]
[[0.14055848 0.01820643]]
[[0.20101532 0.05162425]]
[[0.25366527 0.08320459]]
[[0.3011564  0.11142508]]
263 11
[[-0.4240604  -0.03995569]]
[[-0.27787986 -0.05116996]]
[[-0.13998854 -0.05504447]]
[[-0.02768075 -0.04361358]]
[[ 0.05928962 -0.01907425]]
[[0.12834878 0.01236181]]
[[0.18628564 0.04542238]]
[[0.23734611 0.07691687]]
[[0.28377682 0.10526721]]
[[0.32670105 0.12994456]]
264 10
[[-0.40145016 -0.03350422]]
[[-0.25024098 -0.04632783]]
[[-0.10938731 -0.04816903]]
[[ 0.00348542 -0.03302837]]
[[ 0.09014568 -0.00541922]]
[[0.15902147 0.02766057]]
[[0.21707189 0.06107657]]
[[0.2682693  0.09207822]]
265 8
[[-0.4352927  -0.03184335]]
[[-0.29307452 -0.04319156]]
[[-0.15703735 -0.04944609]]
[[-0.04534782 -0.0415222 ]]
[[ 0.04133642 -0.0202375 ]]
[[0.11001916 0.00883453]]
[[0.16768815 0.04052582]]
[[0.2185911  0.07136061]]
[[0.26511413 0.09964886]]
[[0.30

291 9
[[-0.38728034 -0.03570194]]
[[-0.23993383 -0.04712082]]
[[-0.385742   -0.03583806]]
[[-0.23753875 -0.04738726]]
[[-0.10263056 -0.04872759]]
[[ 0.00438527 -0.03415788]]
[[ 0.08661581 -0.00750919]]
[[0.15251155 0.02475159]]
[[0.20852566 0.05769009]]
[[0.2583535  0.08847381]]
[[0.30379975 0.11578508]]
292 11
[[-0.39995125 -0.03639673]]
[[-0.2468949 -0.0491499]]
[[-0.10405143 -0.05049722]]
[[ 0.01019334 -0.03451651]]
[[ 0.09769866 -0.00596971]]
[[0.16695045 0.02783714]]
[[0.22503632 0.06174246]]
[[0.27604434 0.09292797]]
293 8
[[-0.4272539  -0.03502833]]
[[-0.2836606  -0.04610807]]
[[-0.14662342 -0.05177817]]
[[-0.03459936 -0.04300332]]
[[ 0.0518346  -0.02078401]]
[[0.12010597 0.00912501]]
[[0.17737691 0.04138492]]
[[0.22801569 0.07265033]]
[[0.2741281  0.10107563]]
[[0.31702766 0.12603267]]
294 10
[[-0.41742483 -0.02855147]]
[[-0.27287823 -0.04077199]]
[[-0.13625818 -0.04639225]]
[[-0.02558023 -0.03705317]]
[[ 0.05965268 -0.01449186]]
[[0.12722108 0.01534311]]
[[0.18418328 0.0472406

[[0.10550942 0.00451519]]
[[0.1618891  0.03579907]]
[[0.2116713 0.0665728]]
[[0.25724205 0.09494229]]
[[0.299742   0.12008624]]
[[0.33975467 0.14181547]]
326 11
[[-0.41142496 -0.03320897]]
[[-0.5355071  -0.02739414]]
[[-0.41338652 -0.03298742]]
[[-0.26853114 -0.04510967]]
[[-0.13206059 -0.05007261]]
[[-0.0217515  -0.03972635]]
[[ 0.06294835 -0.01614893]]
[[0.13000575 0.0144751 ]]
[[0.18641236 0.04685976]]
[[0.23630357 0.0777768 ]]
[[0.2819045  0.10566431]]
[[0.32433552 0.12999445]]
327 12
[[-0.4093548  -0.03484851]]
[[-0.26464292 -0.04684332]]
[[-0.12923531 -0.05121469]]
[[-0.02000002 -0.04022549]]
[[ 0.06414241 -0.01620929]]
[[0.13090335 0.0146252 ]]
[[0.18711361 0.04705471]]
[[0.23689115 0.07793201]]
[[0.28223336 0.10570543]]
[[0.3244054  0.12988934]]
328 10
[[-0.3878649 -0.035406 ]]
[[-0.24144237 -0.0478498 ]]
[[-0.10826133 -0.050007  ]]
[[-0.00226835 -0.03615061]]
[[ 0.07945922 -0.01015425]]
[[0.14507794 0.02157818]]
[[0.20084338 0.05407286]]
[[0.25051275 0.08452182]]
[[0.29595488 

[[0.12093771 0.00854612]]
[[0.17770866 0.0408122 ]]
[[0.22781578 0.07191186]]
[[0.27354676 0.10018499]]
[[0.31606236 0.1249659 ]]
356 10
[[-0.39304388 -0.02907914]]
[[-0.24241492 -0.04309522]]
[[-0.10250124 -0.0460396 ]]
[[ 0.00897597 -0.03177235]]
[[ 0.0942232  -0.00480536]]
[[0.16187924 0.02777092]]
[[0.21880864 0.06082989]]
[[0.26903218 0.09148644]]
357 8
[[-0.3977045  -0.03927163]]
[[-0.24815753 -0.05183328]]
[[-0.10963935 -0.0540117 ]]
[[ 0.00114602 -0.03951282]]
[[ 0.08611414 -0.01240686]]
[[0.15339662 0.02044809]]
[[0.20988938 0.05385222]]
[[0.2595773  0.08483167]]
[[0.30474588 0.11220802]]
358 9
[[-0.40505198 -0.02856839]]
[[-0.26310763 -0.04155466]]
[[-0.13156523 -0.04738384]]
[[-0.02585229 -0.03835633]]
[[ 0.05555475 -0.01648445]]
[[0.12043294 0.01248515]]
[[0.17545737 0.04357428]]
[[0.22453582 0.07364665]]
[[0.2695917  0.10102043]]
[[0.26063874 0.0868239 ]]
359 10
[[-0.39362028 -0.03339129]]
[[-0.25237992 -0.04580263]]
[[-0.12375663 -0.05006073]]
[[-0.0208154  -0.03945361]]


[[ 0.00786338 -0.03360736]]
[[ 0.09008832 -0.00723595]]
[[0.15541157 0.02477562]]
[[0.21071818 0.05733626]]
[[0.259996   0.08769254]]
[[0.30495715 0.11452042]]
392 9
[[-0.37785184 -0.03156205]]
[[-0.22910252 -0.04557849]]
[[-0.09317195 -0.04787615]]
[[ 0.01425079 -0.03303669]]
[[ 0.09643745 -0.00581447]]
[[0.16193585 0.02676621]]
[[0.21762815 0.05968754]]
[[0.26697832 0.09012531]]
[[0.31217927 0.11700417]]
393 9
[[-0.37538278 -0.03798448]]
[[-0.22609237 -0.05101744]]
[[-0.09049601 -0.05214202]]
[[ 0.01648358 -0.0362125 ]]
[[ 0.09821486 -0.0081135 ]]
[[0.16325517 0.02511612]]
[[0.21842693 0.05850231]]
[[0.2673718  0.08925457]]
[[0.31196836 0.11625711]]
394 9
[[-0.41209802 -0.03595633]]
[[-0.26943058 -0.04856709]]
[[-0.13564518 -0.05421846]]
[[-0.02726173 -0.04471211]]
[[ 0.05613928 -0.02189145]]
[[0.12231046 0.00823928]]
[[0.1779184  0.04036334]]
[[0.22700086 0.071191  ]]
[[0.27191353 0.0990886 ]]
[[0.31360266 0.12346768]]
395 10
[[-0.42890322 -0.02875238]]
[[-0.2887647  -0.04175472]]
[

[[ 0.07182644 -0.01339524]]
[[0.1385651  0.01841652]]
[[0.19475017 0.05124582]]
[[0.24438773 0.08194414]]
[[0.2897336  0.10924853]]
425 9
[[-0.40274167 -0.02826747]]
[[-0.25732166 -0.04312541]]
[[-0.11954575 -0.04866384]]
[[-0.00862525 -0.03719045]]
[[ 0.07636069 -0.01210903]]
[[0.14336213 0.01947296]]
[[0.1997297  0.05216187]]
[[0.24966502 0.0829237 ]]
[[0.2951157 0.1102398]]
426 9
[[-0.41000697 -0.03027146]]
[[-0.26336756 -0.04534652]]
[[-0.12327789 -0.05102053]]
[[-0.00990885 -0.03947157]]
[[ 0.07697272 -0.01412148]]
[[0.14539629 0.01794199]]
[[0.20251544 0.05104516]]
[[0.2527212  0.08204127]]
[[0.29833412 0.10958419]]
427 9
[[-0.39306653 -0.02903765]]
[[-0.25247657 -0.04239848]]
[[-0.12260552 -0.04825956]]
[[-0.018676   -0.03892051]]
[[ 0.06111927 -0.01655047]]
[[0.1245342  0.01286516]]
[[0.17834987 0.04423099]]
[[0.22636764 0.07433446]]
[[0.27046284 0.10161128]]
[[0.31186616 0.12557018]]
428 10
[[-0.4243269  -0.02893112]]
[[-0.28669122 -0.04125297]]
[[-0.15439782 -0.04967956]]
[[-

[[0.28636092 0.11485564]]
[[0.32560062 0.13614067]]
455 11
[[-0.38674435 -0.02835892]]
[[-0.24282557 -0.04379948]]
[[-0.10870257 -0.04904548]]
[[-0.00210695 -0.03706159]]
[[ 0.0788762  -0.01178304]]
[[0.1430852  0.01978803]]
[[0.19712546 0.05214348]]
[[0.24514687 0.08232879]]
[[0.28909332 0.10906919]]
456 9
[[-0.38351008 -0.0261374 ]]
[[-0.241554   -0.04177582]]
[[-0.11043344 -0.04723224]]
[[-0.00628117 -0.03577717]]
[[ 0.07314232 -0.01120967]]
[[0.13627574 0.01952892]]
[[0.1899961  0.05129664]]
[[0.23785344 0.08094682]]
[[0.2818952  0.10734459]]
457 9
[[-0.42858124 -0.02755542]]
[[-0.29425576 -0.04154481]]
[[-0.16440201 -0.05135278]]
[[-0.05728596 -0.0469781 ]]
[[ 0.02563216 -0.02844693]]
[[ 0.09099639 -0.00129565]]
[[0.14580338 0.029087  ]]
[[0.19444193 0.0591346 ]]
[[0.23901984 0.08685489]]
[[0.28092504 0.11146835]]
[[0.3205139  0.13275832]]
458 11
[[-0.38849384 -0.02494926]]
[[-0.24865305 -0.04083327]]
[[-0.1197722  -0.04732965]]
[[-0.01695499 -0.03744712]]
[[ 0.0618065  -0.0145381

[[-0.26606843 -0.04265896]]
[[-0.13805506 -0.05122173]]
[[-0.26897135 -0.04128212]]
[[-0.13850027 -0.05023699]]
[[-0.03296769 -0.04356817]]
[[ 0.04754034 -0.02272468]]
[[0.11074753 0.00597501]]
[[0.1640113  0.03707669]]
[[0.21152233 0.06717604]]
[[0.25510335 0.09444103]]
[[0.29610467 0.11830317]]
490 14
[[-0.3864244  -0.02857079]]
[[-0.24440728 -0.04536208]]
[[-0.11211438 -0.0511113 ]]
[[-0.00631949 -0.03911652]]
[[ 0.07455825 -0.01376588]]
[[0.1388956  0.01778866]]
[[0.19350815 0.05019703]]
[[0.24202248 0.0804089 ]]
[[0.22836018 0.06326595]]
491 9
[[-0.3617356  -0.02743509]]
[[-0.22002801 -0.04322014]]
[[-0.09198131 -0.04709867]]
[[-0.21071    -0.04463966]]
[[-0.08107898 -0.04693649]]
[[ 0.02041831 -0.03152826]]
[[ 0.09807338 -0.0040721 ]]
[[0.16040336 0.02823455]]
[[0.21367611 0.0604412 ]]
[[0.26128456 0.08996313]]
492 10
[[-0.38136095 -0.02031196]]
[[-0.23757827 -0.0375297 ]]
[[-0.10331975 -0.04398044]]
[[ 0.00332681 -0.03275131]]
[[ 0.08424133 -0.0081206 ]]
[[0.14824043 0.02274253]

[[0.14170201 0.01609243]]
[[0.19408499 0.0476534 ]]
[[0.16813566 0.02582281]]
[[0.22264317 0.05835273]]
[[0.27075803 0.08812999]]
518 10
[[-0.35676545 -0.02843347]]
[[-0.2145297 -0.0447296]]
[[-0.08656594 -0.04946867]]
[[ 0.01342294 -0.03694005]]
[[ 0.08918323 -0.01166905]]
[[0.14941518 0.01937625]]
[[0.20067379 0.05110862]]
[[0.24642277 0.0806261 ]]
[[0.28869966 0.10678072]]
519 9
[[-0.38283452 -0.02194174]]
[[-0.24107458 -0.03957828]]
[[-0.10879467 -0.04726717]]
[[-0.00364969 -0.03751981]]
[[ 0.07596974 -0.01400026]]
[[0.13869387 0.01623174]]
[[0.19147427 0.0477235 ]]
[[0.23856395 0.07745804]]
[[0.28182238 0.10397284]]
520 9
[[-0.39864624 -0.02293905]]
[[-0.26128206 -0.03945938]]
[[-0.13130459 -0.04882924]]
[[-0.02663646 -0.04216772]]
[[ 0.05296341 -0.02140325]]
[[0.11529554 0.00711441]]
[[ 0.06830525 -0.01593059]]
[[0.13340886 0.01418953]]
[[ 0.08968288 -0.00906981]]
[[0.15691285 0.02307534]]
[[0.21270466 0.05562021]]
521 11
[[-0.35840032 -0.02235893]]
[[-0.21674627 -0.03998279]]
[[

547 10
[[-0.35308313 -0.02353408]]
[[-0.21771295 -0.04136698]]
[[-0.09659148 -0.04730063]]
[[-0.00201562 -0.03609556]]
[[ 0.06953801 -0.01245398]]
[[0.12707138 0.01702803]]
[[0.17683116 0.04739233]]
[[0.22224477 0.07594359]]
[[0.20987332 0.05968259]]
548 9
[[-0.351143  -0.0227585]]
[[-0.21617572 -0.04055331]]
[[-0.09471093 -0.04673533]]
[[ 0.00020543 -0.0357763 ]]
[[ 0.07266564 -0.01205989]]
[[0.13112924 0.01770282]]
[[0.18172842 0.04845931]]
[[0.22790325 0.07748024]]
[[0.27103302 0.10337862]]
549 9
[[-0.3777368  -0.01959394]]
[[-0.23969804 -0.03806359]]
[[-0.10946248 -0.04713214]]
[[-0.00575124 -0.0386062 ]]
[[ 0.0727688 -0.0157684]]
[[0.13440707 0.01415484]]
[[0.18666302 0.04564147]]
[[0.23305428 0.07532691]]
[[0.27571455 0.10181963]]
550 9
[[-0.37013045 -0.0224576 ]]
[[-0.2341415 -0.0396332]]
[[-0.10940841 -0.04778881]]
[[-0.01117251 -0.0394921 ]]
[[ 0.06320399 -0.01769666]]
[[-0.00031351 -0.03663497]]
[[ 0.07732446 -0.01290273]]
[[0.13844156 0.01731073]]
[[0.19008036 0.04857104]]
[

[[ 0.05750526 -0.0151944 ]]
[[0.11753941 0.01304825]]
[[0.16853783 0.0430706 ]]
[[0.21452221 0.07178719]]
[[0.25731272 0.09771012]]
579 13
[[-0.33668923 -0.0162953 ]]
[[-0.20014298 -0.03527795]]
[[-0.07835008 -0.0414786 ]]
[[ 0.01550908 -0.02989671]]
[[ 0.08652697 -0.00560577]]
[[ 0.03396672 -0.02587927]]
[[0.10656801 0.00115378]]
[[0.16453373 0.03255774]]
[[0.21454024 0.06354584]]
580 9
[[-0.37953773 -0.01582533]]
[[-0.24866861 -0.03354004]]
[[-0.1262882  -0.04451948]]
[[-0.02907644 -0.03995547]]
[[ 0.04438802 -0.02141811]]
[[0.10212617 0.00514834]]
[[0.1510078  0.03441928]]
[[0.19502398 0.06296507]]
[[0.23586266 0.08900763]]
[[0.27467012 0.11194599]]
581 10
[[-0.36168876 -0.01986407]]
[[-0.22885485 -0.03841731]]
[[-0.10828902 -0.04691722]]
[[-0.01361213 -0.03859549]]
[[ 0.05828938 -0.01698506]]
[[0.11545248 0.01128432]]
[[0.16464904 0.04120476]]
[[0.13906565 0.02021935]]
[[0.19075635 0.05107613]]
[[0.2369483  0.07982915]]
582 10
[[-0.35750228 -0.02574523]]
[[-0.22034612 -0.04460197]]

611 9
[[-0.3528226  -0.02594714]]
[[-0.21951514 -0.04483649]]
[[-0.09854605 -0.05200316]]
[[-0.00361202 -0.04137545]]
[[ 0.06818635 -0.01763068]]
[[0.12524389 0.01230741]]
[[0.17410837 0.04319004]]
[[0.21834132 0.07211202]]
[[0.25960004 0.09784903]]
612 9
[[-0.35154003 -0.01792226]]
[[-0.21748814 -0.03810444]]
[[-0.09537899 -0.04646216]]
[[-4.5761466e-05 -3.6760725e-02]]
[[ 0.07189639 -0.01361674]]
[[0.1291677  0.01587459]]
[[0.17832763 0.04637136]]
[[0.22248115 0.07490157]]
[[0.26329356 0.10020006]]
613 9
[[-0.34578073 -0.01262414]]
[[-0.21603751 -0.03229488]]
[[-0.0993624  -0.04182519]]
[[-0.00894616 -0.03458106]]
[[ 0.05902509 -0.01407458]]
[[0.11330648 0.01327532]]
[[ 0.0761283  -0.00797294]]
[[0.13312495 0.02105236]]
[[0.1823248  0.05100921]]
[[0.22684239 0.07908645]]
614 10
[[-0.3544975  -0.01358223]]
[[-0.22287732 -0.03360509]]
[[-0.10204363 -0.04347416]]
[[-0.00738388 -0.03596097]]
[[ 0.0641812  -0.01458361]]
[[0.12098137 0.01372254]]
[[0.16934317 0.04356568]]
[[0.21313947 0.07

[[0.22253852 0.08751532]]
[[0.25952497 0.10945304]]
644 10
[[-0.33707055 -0.01334741]]
[[-0.21097234 -0.03419135]]
[[-0.09837081 -0.04382639]]
[[-0.01194446 -0.03616169]]
[[ 0.05294362 -0.01518948]]
[[0.1045993 0.0122678]]
[[0.14973125 0.04122431]]
[[0.19158663 0.06877165]]
[[0.23094827 0.09347439]]
645 9
[[-0.346196   -0.01084298]]
[[-0.2205485  -0.03224648]]
[[-0.10565586 -0.04306567]]
[[-0.01567155 -0.03621045]]
[[ 0.05210286 -0.01554095]]
[[0.10621932 0.0121063 ]]
[[0.15315758 0.04138434]]
[[0.19635758 0.06929851]]
[[0.23726715 0.09443406]]
646 9
[[-0.33702755 -0.01740061]]
[[-0.21291652 -0.03688289]]
[[-0.10224292 -0.04613386]]
[[-0.01613826 -0.03888606]]
[[ 0.0488888  -0.01855505]]
[[0.10104667 0.00865253]]
[[0.14649163 0.03767844]]
[[0.1884441  0.06554594]]
[[0.22812237 0.09076384]]
[[0.2658807  0.11273138]]
647 10
[[-0.3547915 -0.0073658]]
[[-0.22700281 -0.0287822 ]]
[[-0.10889797 -0.04068266]]
[[-0.01623886 -0.0351899 ]]
[[ 0.05327309 -0.01555106]]
[[0.10827085 0.01148462]]
[[

[[ 0.08336415 -0.00825034]]
[[0.13678937 0.02017813]]
[[0.18240398 0.04956459]]
[[0.22345354 0.0769956 ]]
677 10
[[-0.30753708 -0.01468751]]
[[-0.1754247  -0.03641571]]
[[-0.06023391 -0.04297839]]
[[ 0.02654925 -0.03076375]]
[[ 0.09105705 -0.00613837]]
[[0.14265607 0.02349689]]
[[0.18771373 0.05320102]]
[[0.22918707 0.08047789]]
678 8
[[-0.34823537 -0.00284201]]
[[-0.22793274 -0.0237462 ]]
[[-0.11815884 -0.03814828]]
[[-0.0328029  -0.03722573]]
[[ 0.03065946 -0.02214287]]
[[0.07986981 0.00123536]]
[[0.12216499 0.02786531]]
[[0.16159588 0.05451433]]
[[0.19907632 0.07928852]]
[[0.23548754 0.10138434]]
[[0.27118006 0.12072573]]
679 11
[[-0.35044846 -0.01200086]]
[[-0.22562578 -0.03367868]]
[[-0.11023643 -0.0462839 ]]
[[-0.01989768 -0.04149545]]
[[ 0.04749011 -0.02212655]]
[[0.10042642 0.0049651 ]]
[[0.14606869 0.03425203]]
[[0.18758461 0.06235339]]
[[0.22674412 0.08772965]]
[[0.26440078 0.10993732]]
680 10
[[-0.3392737  -0.00928327]]
[[-0.21851815 -0.02975466]]
[[-0.34517577 -0.00659308]]

[[-0.10623822 -0.0430222 ]]
[[-0.02550133 -0.04010893]]
[[ 0.03411308 -0.02335184]]
[[-0.01927201 -0.03805111]]
[[ 0.04395835 -0.01996712]]
[[0.09392368 0.00576579]]
[[0.13728684 0.03369912]]
[[0.1771034  0.06053988]]
[[0.21534288 0.08488743]]
712 11
[[-0.31958514 -0.00163186]]
[[-0.19662392 -0.02700775]]
[[-0.08550572 -0.03959359]]
[[-0.00055096 -0.03309341]]
[[ 0.06285927 -0.01256158]]
[[0.11366503 0.01464367]]
[[ 0.084488   -0.00541806]]
[[0.1377725  0.02369715]]
[[0.18387942 0.05296527]]
713 9
[[-0.33728305 -0.01167474]]
[[-0.2147867  -0.03466398]]
[[-0.10216745 -0.04770058]]
[[-0.01447177 -0.04287606]]
[[ 0.05082914 -0.02342069]]
[[0.10198655 0.00357849]]
[[0.14592648 0.03264854]]
[[0.18654644 0.06059745]]
[[0.22463717 0.08571281]]
[[0.26082623 0.10750209]]
714 10
[[-0.29131594 -0.01298521]]
[[-0.16452932 -0.03592335]]
[[-0.05545174 -0.04260331]]
[[ 0.02653424 -0.03033911]]
[[ 0.08807839 -0.00583635]]
[[0.13785103 0.02346198]]
[[0.18140322 0.05268442]]
[[0.22156638 0.07948262]]
71

[[ 0.00640878 -0.0377562 ]]
[[ 0.068357   -0.01512436]]
[[0.11749281 0.01352336]]
[[0.15965694 0.04282207]]
[[0.19847968 0.0700419 ]]
[[0.23551193 0.09406009]]
743 9
[[-0.29033995 -0.00926892]]
[[-0.17389756 -0.03179   ]]
[[-0.07387339 -0.04222719]]
[[ 0.00094714 -0.03535492]]
[[ 0.05651756 -0.01551708]]
[[0.10095415 0.01062638]]
[[0.1405355 0.0383165]]
[[0.17778496 0.06467438]]
[[0.21343973 0.08840066]]
[[0.24827075 0.10906169]]
744 10
[[-0.32204056 -0.01048446]]
[[-0.20307133 -0.03374509]]
[[-0.09563707 -0.04664488]]
[[-0.01315717 -0.04169345]]
[[ 0.04758157 -0.02239311]]
[[0.09581405 0.00434437]]
[[0.1375916  0.03302238]]
[[0.17634626 0.06047655]]
[[0.21344562 0.08519514]]
[[0.24909896 0.10670995]]
745 10
[[-0.3156092  -0.01086571]]
[[-0.19983467 -0.03285769]]
[[-0.09707569 -0.04563225]]
[[-0.01864628 -0.04183518]]
[[ 0.03903968 -0.02432525]]
[[0.0843252  0.00079565]]
[[0.12372038 0.02830472]]
[[0.16044235 0.05503314]]
[[0.19609694 0.07943697]]
[[0.2309592  0.10093264]]
746 10
[[-0.

[[0.18713835 0.07832481]]
[[0.22063231 0.09915733]]
778 10
[[-0.31206328  0.00175551]]
[[-0.19727418 -0.02360072]]
[[-0.09298766 -0.03994915]]
[[-0.01388313 -0.03852709]]
[[ 0.04358201 -0.02203853]]
[[0.08818357 0.00268823]]
[[0.12657544 0.0299627 ]]
[[0.16263087 0.05645354]]
[[0.19773024 0.08053728]]
[[0.23180011 0.10162821]]
779 10
[[-0.31584173 -0.00057699]]
[[-0.19918376 -0.02682613]]
[[-0.09213953 -0.04239372]]
[[-0.01035974 -0.03910783]]
[[ 0.04926907 -0.02078789]]
[[0.0957678  0.00520958]]
[[0.13604087 0.03314749]]
[[0.17375703 0.05992577]]
[[0.20954505 0.08393457]]
780 9
[[-0.2908034  -0.00951499]]
[[-0.17362344 -0.03440256]]
[[-0.0719377  -0.04516815]]
[[ 0.00444924 -0.03717163]]
[[ 0.0604112  -0.01598349]]
[[0.10477276 0.01109625]]
[[0.14405367 0.03926202]]
[[0.18070553 0.06563049]]
[[0.21598406 0.08905645]]
781 9
[[-0.2894845  -0.00387271]]
[[-0.17567231 -0.02851897]]
[[-0.07656625 -0.04120641]]
[[-0.00228723 -0.03587386]]
[[ 0.05209064 -0.01687681]]
[[0.09542992 0.00891129]

[[0.21159483 0.08816968]]
808 9
[[-0.2901913  -0.00300478]]
[[-0.17223854 -0.03060955]]
[[-0.06681414 -0.04368844]]
[[ 0.01232558 -0.03633904]]
[[ 0.07000524 -0.01464395]]
[[0.11559024 0.01335955]]
[[0.1555097  0.04211868]]
[[0.19263138 0.0687393 ]]
809 8
[[-0.27473596  0.00685658]]
[[-0.161129   -0.01985583]]
[[-0.06236027 -0.03458913]]
[[ 0.00993801 -0.03098737]]
[[ 0.06120296 -0.01343196]]
[[0.10133244 0.01114912]]
[[0.13721204 0.03761255]]
[[0.17163563 0.06306394]]
[[0.20573518 0.08611318]]
810 9
[[-0.28260267 -0.00832077]]
[[-0.16609551 -0.03419193]]
[[-0.06474744 -0.04587828]]
[[ 0.01019245 -0.03839184]]
[[ 0.06450581 -0.01724404]]
[[0.10737623 0.01002758]]
[[0.14510727 0.03817954]]
[[0.18062112 0.0645008 ]]
[[0.21429911 0.08767449]]
811 9
[[-0.26847744  0.00413948]]
[[-0.15547399 -0.02285557]]
[[-0.0592032  -0.03603943]]
[[ 0.0107958  -0.03035384]]
[[ 0.06057153 -0.01124451]]
[[0.09981277 0.01410944]]
[[0.13517444 0.04068333]]
[[0.1693395  0.06578215]]
[[0.20337135 0.08825507]]


[[-0.05754303 -0.0390456 ]]
[[ 0.00673095 -0.03332429]]
[[ 0.05292019 -0.01427275]]
[[ 0.01614545 -0.030577  ]]
[[ 0.06535466 -0.0093645 ]]
[[0.10507558 0.01726487]]
[[0.14094187 0.04448137]]
[[0.17541593 0.06960346]]
840 10
[[-0.28001052  0.00242137]]
[[-0.17374273 -0.02428206]]
[[-0.08158665 -0.0394531 ]]
[[-0.01347088 -0.03670412]]
[[ 0.03532197 -0.02013084]]
[[0.07360607 0.00356552]]
[[0.10791387 0.02939032]]
[[0.1414279  0.05442572]]
[[0.17491356 0.0773249 ]]
[[0.2082455  0.09747533]]
841 10
[[-0.27341872 -0.00140035]]
[[-0.1619394  -0.02919982]]
[[-0.06457132 -0.04279878]]
[[ 0.00766349 -0.03668113]]
[[ 0.06025078 -0.01649111]]
[[0.10211317 0.01011453]]
[[0.13949305 0.03788541]]
[[0.17501427 0.06393887]]
[[0.20955703 0.08713238]]
842 9
[[-0.2726432   0.01288713]]
[[-0.1657665  -0.01382142]]
[[-0.07278982 -0.03138322]]
[[-0.00524854 -0.03189986]]
[[ 0.04181024 -0.018092  ]]
[[0.0776118 0.0038587]]
[[ 0.05086567 -0.01385987]]
[[ 0.0084653  -0.02779178]]
[[ 0.06151782 -0.00955668]]


[[ 0.02755255 -0.02551928]]
[[ 0.06354521 -0.00383327]]
[[0.09522223 0.02106956]]
[[0.12595423 0.04588411]]
[[0.11485653 0.02948763]]
[[0.14917304 0.05494252]]
[[0.18278754 0.07793599]]
869 11
[[-0.27658218 -0.00450769]]
[[-0.1695995  -0.03231061]]
[[-0.07622932 -0.046841  ]]
[[-0.00741354 -0.04218296]]
[[ 0.04244363 -0.02329451]]
[[0.08202183 0.002474  ]]
[[ 0.0561096  -0.01804945]]
[[0.09931225 0.0092765 ]]
[[0.13794371 0.03739981]]
[[0.17456076 0.06347304]]
870 10
[[-0.27768633  0.00493745]]
[[-0.3671322   0.02796094]]
[[-0.27244365  0.00229107]]
[[-0.16135706 -0.02703261]]
[[-0.06351233 -0.04230896]]
[[ 0.0088404  -0.03748311]]
[[ 0.06037008 -0.01815019]]
[[0.10035269 0.00783746]]
[[ 0.07540356 -0.01244551]]
[[0.1184019  0.01534402]]
[[0.1560885  0.04338995]]
871 11
[[-0.24731478 -0.00129115]]
[[-0.13667089 -0.02957153]]
[[-0.0436351  -0.04159996]]
[[ 0.02309317 -0.03374539]]
[[ 0.07056686 -0.01268163]]
[[0.10787942 0.01386851]]
[[ 0.08510122 -0.00648604]]
[[0.12544085 0.02182554]]

[[-0.24988683  0.00109234]]
[[-0.14520052 -0.02714882]]
[[-0.05656478 -0.04132423]]
[[ 0.00742953 -0.03630674]]
[[-0.05156944 -0.0411015 ]]
[[ 0.01472595 -0.0344448 ]]
[[ 0.06222983 -0.01407664]]
[[0.09988322 0.01220516]]
[[0.13363728 0.03917195]]
[[0.16636156 0.06429584]]
[[0.19883764 0.08648178]]
900 13
[[-0.24486831  0.01381202]]
[[-0.14066131 -0.01522461]]
[[-0.05291276 -0.03205167]]
[[ 0.00851111 -0.03037298]]
[[ 0.05019439 -0.01455013]]
[[0.08233076 0.00839829]]
[[0.11195578 0.03343582]]
[[0.14134686 0.05760746]]
[[0.17126392 0.07958231]]
901 9
[[-0.2753725   0.00807559]]
[[-0.17313237 -0.0201042 ]]
[[-0.08281855 -0.03859977]]
[[-0.01620724 -0.03915092]]
[[ 0.03075472 -0.02466782]]
[[ 0.06723583 -0.00189512]]
[[0.09951444 0.02362924]]
[[0.13096377 0.04861386]]
[[0.16248219 0.07149133]]
[[0.19378497 0.09159908]]
902 10
[[-0.24427079  0.01100112]]
[[-0.14187783 -0.01749942]]
[[-0.0559753  -0.03395813]]
[[ 0.00466617 -0.03241817]]
[[ 0.04662075 -0.01714175]]
[[0.0793929  0.00525702]

[[ 0.00506338 -0.03610612]]
[[ 0.04433179 -0.02113922]]
[[0.07500987 0.00113329]]
[[0.10250203 0.02557791]]
[[0.12944023 0.04929535]]
[[0.15786822 0.07098688]]
[[0.1873395  0.09022179]]
935 10
[[-0.24093461  0.00479024]]
[[-0.13663381 -0.02604935]]
[[-0.04805262 -0.0422027 ]]
[[ 0.01494583 -0.03815472]]
[[ 0.05877057 -0.01963265]]
[[0.0925456  0.00547335]]
[[0.1235546  0.03182211]]
[[0.15421808 0.05673113]]
[[0.18518007 0.07885323]]
936 9
[[-0.23365705  0.00427137]]
[[-0.12905823 -0.02651075]]
[[-0.04124231 -0.04166881]]
[[ 0.02022166 -0.03656127]]
[[-0.03543878 -0.04280252]]
[[ 0.02757164 -0.03501589]]
[[ 0.07172395 -0.01375812]]
[[0.10683396 0.01287704]]
[[ 0.08788841 -0.0072687 ]]
[[0.12651359 0.02110389]]
937 10
[[-0.2227901  0.0092519]]
[[-0.1194334 -0.0215215]]
[[-0.03395261 -0.03689629]]
[[ 0.02583896 -0.03233185]]
[[ 0.06714137 -0.01399617]]
[[0.09993617 0.01058228]]
[[0.13002896 0.03633926]]
[[0.16030455 0.0606571 ]]
[[0.19020198 0.08226234]]
938 9
[[-0.24136746  0.01926456]]


[[0.11760803 0.03880662]]
[[0.14514345 0.06225067]]
[[0.17332496 0.08302741]]
966 9
[[-0.20760477  0.01192524]]
[[-0.11062819 -0.01865172]]
[[-0.20515922  0.00942008]]
[[-0.1078181  -0.02092746]]
[[-0.03050843 -0.03429798]]
[[ 0.02171855 -0.02816864]]
[[ 0.05767663 -0.00940997]]
[[0.0867441  0.01472978]]
[[0.11510642 0.03959505]]
[[0.1440762  0.06287974]]
[[0.17386925 0.08358619]]
967 11
[[-0.24114992  0.00690891]]
[[-0.14386424 -0.02316252]]
[[-0.06156379 -0.04014137]]
[[-0.00307236 -0.0380569 ]]
[[ 0.0370709  -0.02184561]]
[[0.06877285 0.00153384]]
[[0.09784272 0.02675853]]
[[0.12659693 0.05095701]]
[[0.1556605  0.07260386]]
[[0.18517564 0.09151299]]
968 10
[[-0.21785066  0.01376401]]
[[-0.11915622 -0.01765685]]
[[-0.03844669 -0.03322817]]
[[ 0.01688589 -0.02919463]]
[[ 0.05476886 -0.01178697]]
[[0.08465353 0.0116315 ]]
[[0.11314623 0.03627299]]
[[0.14166266 0.05953912]]
[[0.13688926 0.04591247]]
969 9
[[-0.23480913  0.01461863]]
[[-0.13393095 -0.01817189]]
[[-0.04704177 -0.03670986]